version: '3'

services:
  telegram-forwarder:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - SOURCE=${SOURCE}
      - DESTINATION_CHANNEL=${DESTINATION_CHANNEL}
      - TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING}
      - PYTHONUNBUFFERED=true
      - RENDER=true
    volumes:
      - tmp_data:/tmp
    restart: unless-stopped

volumes:
  tmp_data:
