services:
    - type: web
      name: telegram-forwarder
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app
      autoDeploy: false
      envVars:
          - key: TELEGRAM_API_ID
            sync: false
          - key: TELEGRAM_API_HASH
            sync: false
          - key: SOURCE
            sync: false
          - key: DESTINATION_CHANNEL
            sync: false
      healthCheckPath: /health
      plan: free
