services:
    - type: web
      name: telegram-forwarder
      env: docker
      dockerfilePath: ./Dockerfile
      autoDeploy: false
      disk:
          name: temp
          mountPath: /tmp
          sizeGB: 1
      envVars:
          - key: TELEGRAM_API_ID
            sync: false
          - key: TELEGRAM_API_HASH
            sync: false
          - key: SOURCE
            sync: false
          - key: DESTINATION_CHANNEL
            sync: false
          - key: TELEGRAM_SESSION_STRING
            sync: false
          - key: PYTHONUNBUFFERED
            value: "true"
          - key: RENDER
            value: "true"
      healthCheckPath: /health
      plan: free
