services:
    - type: web
      name: telegram-forwarder
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --log-file -
      autoDeploy: false
      disk:
          name: temp
          mountPath: /tmp
          sizeGB: 1
      envVars:
          - key: TELEGRAM_API_ID
            sync: false
          - key: TELEGRAM_API_HASH
            sync: false
          - key: SOURCE
            sync: false
          - key: DESTINATION_CHANNEL
            sync: false
          - key: TELEGRAM_SESSION_STRING
            sync: false
          - key: PYTHONUNBUFFERED
            value: "true"
          - key: RENDER
            value: "true"
      healthCheckPath: /health
      plan: free
